# Generated by Django 2.2.17 on 2021-01-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_schedule_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='id',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='number',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='人数'),
        ),
    ]
